In [12]:
import pandas as pd
pd.set_option('display.max_columns',50)
test_data = pd.read_csv('test.csv')
train_data = pd.read_csv('train.csv')
train_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1379.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,567.240411,1057.429452,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,6.517808,0.613014,1978.506164,1.767123,472.980137,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,441.866955,438.705324,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,1.625393,0.644666,24.689725,0.747315,213.804841,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,223.000000,795.750000,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1961.000000,1.000000,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,477.500000,991.500000,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1980.000000,2.000000,480.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,808.000000,1298.250000,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,2010.000000,4.000000,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [13]:
train_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [55]:
y = train_data.SalePrice
features = ['LotArea','OverallCond','OverallQual','GarageCars','BedroomAbvGr','1stFlrSF', '2ndFlrSF','GrLivArea','TotRmsAbvGrd']
X = train_data[features]
X.describe()

,LotArea,OverallCond,OverallQual,GarageCars,BedroomAbvGr,1stFlrSF,2ndFlrSF,GrLivArea,TotRmsAbvGrd
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,5.575342,6.099315,1.767123,2.866438,1162.626712,346.992466,1515.463699,6.517808
std,9981.264932,1.112799,1.382997,0.747315,0.815778,386.587738,436.528436,525.480383,1.625393
min,1300.000000,1.000000,1.000000,0.000000,0.000000,334.000000,0.000000,334.000000,2.000000
25%,7553.500000,5.000000,5.000000,1.000000,2.000000,882.000000,0.000000,1129.500000,5.000000
50%,9478.500000,5.000000,6.000000,2.000000,3.000000,1087.000000,0.000000,1464.000000,6.000000
75%,11601.500000,6.000000,7.000000,2.000000,3.000000,1391.250000,728.000000,1776.750000,7.000000
max,215245.000000,9.000000,10.000000,4.000000,8.000000,4692.000000,2065.000000,5642.000000,14.000000

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error

train_X,val_X,train_y,val_y = train_test_split(X,y, random_state = 1)
my_model = DecisionTreeRegressor(max_leaf_nodes = 86,random_state=1)
my_model.fit(train_X,train_y)
val_preds = my_model.predict(val_X)
print("Decision tree MAE:")
print(mean_absolute_error(val_y,val_preds))

def get_mae(max_leaf_nodes,train_X,val_X,train_y,val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes,random_state=1)
    model.fit(train_X,train_y)
    preds_val = model.predict (val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return mae

for max_leaf_nodes in range(70,110,2):
    my_mae = get_mae(max_leaf_nodes,train_X,val_X,train_y,val_y)
    print('MAx leaf nodes :%d \t\t MAE:%d'%(max_leaf_nodes,my_mae))

Decision tree MAE:
22041.603408354287
MAx leaf nodes :70 		 MAE:22327
MAx leaf nodes :72 		 MAE:22233
MAx leaf nodes :74 		 MAE:22200
MAx leaf nodes :76 		 MAE:22182
MAx leaf nodes :78 		 MAE:22204
MAx leaf nodes :80 		 MAE:22258
MAx leaf nodes :82 		 MAE:22055
MAx leaf nodes :84 		 MAE:22056
MAx leaf nodes :86 		 MAE:22041
MAx leaf nodes :88 		 MAE:22074
MAx leaf nodes :90 		 MAE:22185
MAx leaf nodes :92 		 MAE:22171
MAx leaf nodes :94 		 MAE:22182
MAx leaf nodes :96 		 MAE:22109
MAx leaf nodes :98 		 MAE:22071
MAx leaf nodes :100 		 MAE:22235
MAx leaf nodes :102 		 MAE:22370
MAx leaf nodes :104 		 MAE:22439
MAx leaf nodes :106 		 MAE:22471
MAx leaf nodes :108 		 MAE:22574

In [57]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X,train_y)
f_val_preds = forest_model.predict(val_X)
print("random forest MAE:")
print(mean_absolute_error(f_val_preds,val_y))

random forest MAE:
19612.97324331376

In [63]:
rf_model_on_full_data = RandomForestRegressor(random_state = 1)
rf_model_on_full_data.fit(train_X, train_y)
test_X = test_data[features]
na_value = test_X['GarageCars'].median()
test_X['GarageCars'] = test_X['GarageCars'].fillna(na_value)
test_X.describe()

<ipython-input-63-c99dc691984d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_X['GarageCars'] = test_X['GarageCars'].fillna(na_value)

,LotArea,OverallCond,OverallQual,GarageCars,BedroomAbvGr,1stFlrSF,2ndFlrSF,GrLivArea,TotRmsAbvGrd
count,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,9819.161069,5.553804,6.078821,1.766278,2.854010,1156.534613,325.967786,1486.045922,6.385195
std,4955.517327,1.113740,1.436812,0.775703,0.829788,398.165820,420.610226,485.566099,1.508895
min,1470.000000,1.000000,1.000000,0.000000,0.000000,407.000000,0.000000,407.000000,3.000000
25%,7391.000000,5.000000,5.000000,1.000000,2.000000,873.500000,0.000000,1117.500000,5.000000
50%,9399.000000,5.000000,6.000000,2.000000,3.000000,1079.000000,0.000000,1432.000000,6.000000
75%,11517.500000,6.000000,7.000000,2.000000,3.000000,1382.500000,676.000000,1721.000000,7.000000
max,56600.000000,9.000000,10.000000,5.000000,6.000000,5095.000000,1862.000000,5095.000000,15.000000

In [64]:
test_preds = rf_model_on_full_data.predict(test_X)
print(test_preds)


# The lines below shows how to save predictions in format used for competition scoring
output = pd.DataFrame({'Id': test_data.Id,
                      'SalePrice': test_preds})
output.to_csv('submission.csv', index=False)

[120788.   159149.91 162483.87 ... 153255.69 122929.   243557.16]